
@Labb_2_HostAddress = http://localhost:5013

GET {{Labb_2_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{Labb 2_HostAddress}}/api/author
Accept: application/json
###

GET {{Labb 2_HostAddress}}/api/book

###
